function openSection(id,btn){document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.mainTab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');setTimeout(()=>map.invalidateSize(),100);}
const colors=['#d32f2f','#1976d2','#388e3c','#f57c00','#7b1fa2'];let currentWeather=0;
const map=L.map('map').setView([-23.2,-45.9],9);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);const allLayer=L.layerGroup().addTo(map);let allCoords=[];
function nav(a){return 'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(a)}
async function geo(q){try{const r=await fetch('https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=br&q='+encodeURIComponent(q),{headers:{'Accept-Language':'pt-BR'}});const a=await r.json();return a.length?[+a[0].lat,+a[0].lon]:null}catch(e){return null}}
async function buildMap(){const box=document.getElementById('points');for(let di=0;di<routeDays.length;di++){const d=routeDays[di],coords=[];for(let pi=0;pi<d.points.length;pi++){const [name,address]=d.points[pi],c=await geo(address);if(c){coords.push(c);allCoords.push(c);L.circleMarker(c,{radius:8,weight:3,color:colors[di],fillColor:colors[di],fillOpacity:.9}).addTo(allLayer).bindPopup('<b>Dia '+(di+1)+' — Ponto '+(pi+1)+'</b><br><strong>'+name+'</strong><br>'+address+'<br><br><a target="_blank" href="'+nav(address)+'">🚶 Abrir navegação</a>')}const row=document.createElement('div');row.className='point';row.innerHTML='<span class="num" style="background:'+colors[di]+'">'+(di+1)+'.'+(pi+1)+'</span><div><b>'+name+'</b><br><small>'+address+'</small></div><a target="_blank" href="'+nav(address)+'">Navegar</a>';box.appendChild(row)}if(coords.length>1)L.polyline(coords,{color:colors[di],weight:5,opacity:.72}).addTo(allLayer)}if(allCoords.length)map.fitBounds(allCoords,{padding:[25,25]})}
function locateMe(){if(!navigator.geolocation)return alert('Seu navegador não permite localização.');navigator.geolocation.getCurrentPosition(p=>{const c=[p.coords.latitude,p.coords.longitude];L.circleMarker(c,{radius:10,color:'#000',weight:3,fillOpacity:.85}).addTo(allLayer).bindPopup('📍 Você está aqui').openPopup();map.setView(c,15)},()=>alert('Não foi possível obter sua localização. Verifique a permissão de localização.'))}
const weatherLocations=[{name:"Santo André → Arujá",lat:-23.6560,lon:-46.5278},{name:"Arujá → Jacareí",lat:-23.3950,lon:-46.3200},{name:"Jacareí → Caçapava",lat:-23.0650,lon:-45.7100},{name:"Caçapava → Pindamonhangaba",lat:-22.9000,lon:-45.4600},{name:"Pindamonhangaba → Aparecida",lat:-22.8600,lon:-45.2300}];let dynamicWeather=[],lastUpdated=null;
function isoDateForDay(i){return '2026-10-'+String(6+i).padStart(2,'0')}
function weatherCodeText(c){if(c===0)return'☀️ Céu limpo';if([1,2,3].includes(c))return'🌤️ Nublado/parcialmente nublado';if([45,48].includes(c))return'🌫️ Neblina';if([51,53,55,56,57].includes(c))return'🌦️ Chuvisco';if([61,63,65,66,67].includes(c))return'🌧️ Chuva';if([71,73,75,77].includes(c))return'🌨️ Precipitação';if([80,81,82].includes(c))return'🌧️ Pancadas';if([95,96,99].includes(c))return'⛈️ Trovoada';return'☁️ Condição variável'}
function riskFrom(p,mm,c){if(c>=95||p>=80||mm>=5)return'🔴 Alto';if(p>=50||mm>=2)return'🟠 Moderado/alto';if(p>=25||mm>=.5)return'🟡 Moderado';return'🟢 Baixo'}
function dayRisk(rows){const p=Math.max(...rows.map(x=>x.prob)),mm=rows.reduce((a,x)=>a+x.mm,0),t=rows.some(x=>x.code>=95);if(t||p>=80||mm>=10)return['🔴 ALTO','Há janela importante de chuva/instabilidade.'];if(p>=50||mm>=3)return['🟠 MODERADO/ALTO','Há risco relevante de chuva durante o percurso.'];if(p>=25||mm>=1)return['🟡 MODERADO','Chuva possível, mas sem sinal de risco elevado.'];return['🟢 BAIXO','Baixa probabilidade de chuva na janela analisada.']}
async function fetchWeatherDay(i){const loc=weatherLocations[i],date=isoDateForDay(i),u='https://api.open-meteo.com/v1/forecast?latitude='+loc.lat+'&longitude='+loc.lon+'&hourly=temperature_2m,apparent_temperature,precipitation_probability,precipitation,weather_code,wind_speed_10m,wind_gusts_10m&timezone=America%2FSao_Paulo&start_date='+date+'&end_date='+date;const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error('API '+r.status);const j=await r.json(),rows=[];for(let k=0;k<j.hourly.time.length;k++){const h=Number(j.hourly.time[k].slice(11,13));if(h>=6&&h<=20)rows.push({hour:h,temp:Math.round(j.hourly.temperature_2m[k]),feels:Math.round(j.hourly.apparent_temperature[k]),prob:Math.round(j.hourly.precipitation_probability[k]??0),mm:Number(j.hourly.precipitation[k]??0),code:Number(j.hourly.weather_code[k]??0),wind:Math.round(j.hourly.wind_speed_10m[k]??0),gust:Math.round(j.hourly.wind_gusts_10m[k]??0)})}return{loc,rows}}
function updateWeatherBadge(msg){let e=document.getElementById('autoStatus');if(!e){e=document.createElement('div');e.id='autoStatus';e.style.cssText='background:#e8f5e9;color:#1b5e20;padding:9px 12px;border-radius:9px;font-size:12px;margin-bottom:10px;font-weight:bold';document.querySelector('.wrap').prepend(e)}e.textContent='🌐 '+msg+(lastUpdated?' • '+lastUpdated.toLocaleString('pt-BR'):'')}
async function updateWeatherFromApi(){updateWeatherBadge('Atualizando previsão pela internet...');try{dynamicWeather=await Promise.all(weatherLocations.map((_,i)=>fetchWeatherDay(i)));lastUpdated=new Date();updateWeatherBadge('Previsão atualizada automaticamente');renderWeather();renderOverview()}catch(e){console.error(e);updateWeatherBadge('Falha na atualização — recarregue a página');renderWeather();renderOverview()}}
function renderWeather(){document.getElementById('weatherTabs').innerHTML=routeDays.map((x,i)=>'<button class="dayTab '+(i===currentWeather?'active':'')+'" onclick="currentWeather='+i+';renderWeather()">DIA '+(i+1)+' — '+String(6+i).padStart(2,'0')+'/10</button>').join('');const d=routeDays[currentWeather],w=dynamicWeather[currentWeather];document.getElementById('weatherTitle').textContent=d.title;if(!w){document.getElementById('weatherStats').innerHTML='<div class="stat"><b>Aguardando...</b><small>previsão automática</small></div>';document.getElementById('weatherHours').innerHTML='<tr><td colspan="5">Consultando a previsão meteorológica...</td></tr>';document.getElementById('weatherNote').textContent='🌐 Aguarde a atualização automática da previsão.';return}const rows=w.rows,temps=rows.map(x=>x.temp),maxP=Math.max(...rows.map(x=>x.prob)),total=rows.reduce((a,x)=>a+x.mm,0),risk=dayRisk(rows);document.getElementById('weatherStats').innerHTML='<div class="stat"><b>'+d.distance+'</b><small>distância</small></div><div class="stat"><b>'+Math.min(...temps)+'–'+Math.max(...temps)+' °C</b><small>temperatura 06–20h</small></div><div class="stat"><b>'+maxP+'%</b><small>maior chance de chuva</small></div><div class="stat"><b>'+total.toFixed(1)+' mm</b><small>chuva prevista 06–20h</small></div><div class="stat"><b>'+risk[0]+'</b><small>risco prático</small></div>';document.getElementById('weatherNote').textContent='🌐 Previsão atualizada automaticamente. Referência: '+w.loc.name+'. Última atualização: '+(lastUpdated?lastUpdated.toLocaleString('pt-BR'):'—')+'.';document.getElementById('weatherHours').innerHTML=rows.map(x=>'<tr><td><b>'+String(x.hour).padStart(2,'0')+'h</b></td><td>'+x.temp+' °C</td><td>'+x.prob+'%</td><td>'+weatherCodeText(x.code)+'<br><small>'+x.mm.toFixed(1)+' mm • sensação '+x.feels+'°</small></td><td>'+riskFrom(x.prob,x.mm,x.code)+'</td></tr>').join('');document.getElementById('weatherTip').innerHTML='<b>'+risk[0]+'</b> — '+risk[1]+'<br><br>💨 Vento máximo: '+Math.max(...rows.map(x=>x.wind))+' km/h; rajadas até '+Math.max(...rows.map(x=>x.gust))+' km/h.<br>📍 A previsão representa um ponto de referência do trecho e pode variar ao longo da rota.'}
function renderOverview(){if(dynamicWeather.length!==5){document.getElementById('overview').innerHTML='<div class="dayCard"><b>Atualizando...</b><small>A previsão dos cinco dias será exibida aqui.</small></div>';return}document.getElementById('overview').innerHTML=dynamicWeather.map((w,i)=>{const rows=w.rows,t=rows.map(x=>x.temp),p=Math.max(...rows.map(x=>x.prob)),r=dayRisk(rows)[0];return'<div class="dayCard"><b>DIA '+(i+1)+' — '+String(6+i).padStart(2,'0')+'/10</b><small>'+routeDays[i].title.split(' — ')[1]+'<br>'+routeDays[i].distance+'<br>🌡️ '+Math.min(...t)+'–'+Math.max(...t)+' °C<br>🌧️ até '+p+'%<br>'+r+'</small></div>'}).join('')}
buildMap();renderWeather();renderOverview();updateWeatherFromApi();